/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Lexyc16 (https://sketchfab.com/Lexyc16)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tesla-cybertruck-f12e67159f75486bb21213e573520612
Title: Tesla Cybertruck
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props: any) {
  const { nodes, materials } = useGLTF("/models/tesla_cybertruck.glb") as any;
  return (
    <group {...props} dispose={null}>
      <group name="Cube001_6" position={[1.848, 0.859, 0.807]} scale={0.452}>
        <mesh
          name="Object_4"
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Material}
        />
        <mesh
          name="Object_5"
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="Object_6"
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          name="Object_7"
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          name="Object_8"
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          name="Object_9"
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group
        name="Circle_7"
        position={[2.345, 0.455, -0.249]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.244, 0.263, 0.244]}
      >
        <mesh
          name="Object_11"
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          name="Object_12"
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group
        name="Circle001_8"
        position={[2.345, 0.455, 1.869]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.244, 0.263, 0.244]}
      >
        <mesh
          name="Object_14"
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          name="Object_15"
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group
        name="Circle002_9"
        position={[1.348, 0.455, 1.869]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[0.244, 0.263, 0.244]}
      >
        <mesh
          name="Object_17"
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          name="Object_18"
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group
        name="Circle003_10"
        position={[1.348, 0.455, -0.249]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[0.244, 0.263, 0.244]}
      >
        <mesh
          name="Object_20"
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          name="Object_21"
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials["Material.007"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/tesla_cybertruck.glb");
